# Generated by Django 3.2 on 2021-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('waiting', 'Waiting for orders')], default='waiting', max_length=100),
        ),
    ]
