# Generated by Django 3.2 on 2021-05-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
